In [1]:
from art.estimators.speech_recognition import PyTorchDeepSpeech

In [2]:
ds2 = PyTorchDeepSpeech(pretrained_model="librispeech", clip_values=[-1, 1])

/home/rni/.anaconda3/envs/torch/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (WordErrorRate). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
/home/rni/.anaconda3/envs/torch/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 i

In [3]:
from art.attacks.evasion import ProjectedGradientDescentPyTorch, ProjectedGradientDescent, ImperceptibleASRPyTorch

In [9]:
pgd = ProjectedGradientDescent(ds2, norm='inf', eps=0.01, eps_step=0.002, max_iter=7)

In [10]:
from scipy.io import wavfile
import numpy as np
samplerate, data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/36_benign.wav')
adv = pgd.generate(np.array([data]))

PGD - Iterations:   0%|          | 0/7 [00:00<?, ?it/s]

In [20]:
samplerate, data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/36_benign.wav')
samplerate

16000

In [11]:
data, adv

(array([-6.1035156e-05,  6.1035156e-05,  6.1035156e-05, ...,
         1.5258789e-04,  1.5258789e-04,  2.1362305e-04], dtype=float32),
 array([[ 0.00993896,  0.00206104, -0.00193896, ..., -0.00184741,
         -0.00984741,  0.00221362]], dtype=float32))

In [12]:
ds2.predict(x = np.array([data]), batch_size= 1)

array(["AND ALL HIS BROTHERS AND SISTERS STOOD ROUND AND LISTENED WITH THEIR MOUTH'S OPEN"],
      dtype='<U81')

In [13]:
ds2.predict(x = adv, batch_size= 1)

array(['AND ROBED AS RELLEGED AND FLIFFT TO UNDERSTOOD ROUND IF I ERITTEN WICKER AND MORAL DRAINWAILT'],
      dtype='<U93')

In [15]:
wavfile.write("saved_adv/0.wav", samplerate, adv.T)

In [26]:
samplerate, data = wavfile.read('/home/rni/IDL_project/saved_adv/0.wav')
ds2.predict(x = np.array([data]), batch_size= 1)

array(['AND ROBED AS RELLERGED AND FLIFFT TO UNDERSTOOD ROUND IF I ERITTEN WICKER AND MORAL DRAINWAILT'],
      dtype='<U94')

In [35]:
samplerate, data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T051608.443297/reconstructed_low_sampled/0_adversarial_gen.wav')
data = data.astype(np.float32)
max_int16 = 2**17
data = data / max_int16
data
ds2.predict(x = np.array([data]), batch_size= 1)

array(['BRIHTER THAN EARLY DAWNS  MOST BRILLIANT DIE ARE BLOWN CLEAR BANCE OF COLOR THROUGH THE SKY THAT SWIRL AND SWEEP AND MATE TO BREAK AND FOAM LIKE RAINBOW VILLES UPON A BOVLS STONE'],
      dtype='<U178')

array([-0.00152588, -0.00158691, -0.00079346, ..., -0.0005188 ,
       -0.00045776, -0.00015259], dtype=float32)

In [32]:
samplerate, before_recons_data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T051608.443297/saved_samples/0_adversarial.wav')
ds2.predict(x = np.array([before_recons_data]), batch_size= 1)

/home/rni/deepspeech.pytorch/deepspeech_pytorch/model.py:310: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  seq_len = ((seq_len + 2 * m.padding[1] - m.dilation[1] * (m.kernel_size[1] - 1) - 1) // m.stride[1] + 1)


array(['BRIGHTER THAN EARLY DAWNS  MOST BRILLIANT DYE ARE BLOWN CLEAR BANDS OF COLOR THROUGH THE SKY THAT SWIRLN AND SWEEP AND MATE TO BREAK AND FOAM LIKE RAINBOW VELLES UPON A BOVVLE STONE'],
      dtype='<U181')

In [31]:
before_recons_data

array([ 0.0006    ,  0.00056948, -0.00016948, ...,  0.00047793,
       -0.00032207,  0.00050845], dtype=float32)

In [12]:
from scipy.io import wavfile
import numpy as np

In [24]:
samplerate, data = wavfile.read('/home/rni/ParallelWaveGAN/output_sample/36_adversarial_16000_gen.wav')
data = data.astype(np.float32)
max_int16 = 2**15
data = data / max_int16
hifigan = ds2.predict(x = np.array([data]), batch_size= 1)
ds2.predict(x = np.array([data]), batch_size= 1)

array(['AND ALL TIS ROBBEN LITE CWISCAN STOOD ROUND AND LISTENED WITH HIM LOVES OLTEM'],
      dtype='<U77')

In [15]:
samplerate, data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/36_adversarial.wav')
adv = ds2.predict(x = np.array([data]), batch_size= 1)
data

array([-0.00206104, -0.00193896,  0.00206104, ...,  0.01015259,
       -0.00184741, -0.00578638], dtype=float32)

In [16]:
samplerate, data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/36_benign.wav')
benign = ds2.predict(x = np.array([data]), batch_size= 1)

In [17]:
from jiwer import wer

wer(benign[0], adv[0])

0.7142857142857143

In [18]:
wer(benign[0], hifigan[0])

0.5

In [19]:
hifigan, adv, benign

(array(['AND ALL TIS ROBBEN LITE CWISCAN STOOD ROUND AND LISTENED WITH HIM LOVES OLTEM'],
       dtype='<U77'),
 array(['AND ALL TI ROBER LEOKE WITHCIN STOOD ROUND ANDELITTENED WITH HIM LOVES ON THEM'],
       dtype='<U78'),
 array(["AND ALL HIS BROTHERS AND SISTERS STOOD ROUND AND LISTENED WITH THEIR MOUTH'S OPEN"],
       dtype='<U81'))

In [19]:
import pickle
with open ('gt.pkl', 'rb') as fp:
    strings = pickle.load(fp)

In [ ]:
strings

In [20]:
from jiwer import wer

wer(strings[36].decode(), adv[0]), wer(strings[36].decode(), hifigan[0]), wer(strings[36].decode(), benign[0])

(0.7142857142857143, 0.5, 0.07142857142857142)

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

ds = tfds.load('librispeech', split='test_clean', data_dir='/data/armory_datasets/', download=False)

In [2]:
ds

<PrefetchDataset element_spec={'chapter_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'id': TensorSpec(shape=(), dtype=tf.string, name=None), 'speaker_id': TensorSpec(shape=(), dtype=tf.int64, name=None), 'speech': TensorSpec(shape=(None,), dtype=tf.int16, name=None), 'text': TensorSpec(shape=(), dtype=tf.string, name=None)}>

In [3]:
ds = tfds.as_numpy(ds)

In [4]:
index = 0
strings = []
for data in ds:
    if index == 100:
        break
    strings.append(data['text'])
    index += 1

In [19]:
strings

[b"BRIGHTER THAN EARLY DAWN'S MOST BRILLIANT DYE ARE BLOWN CLEAR BANDS OF COLOR THROUGH THE SKY THAT SWIRL AND SWEEP AND MEET TO BREAK AND FOAM LIKE RAINBOW VEILS UPON A BUBBLE'S DOME",
 b'I AM NOT GOOD ENOUGH FOR YOU AND YOU MUST BE KEPT FROM THE CONTAMINATION OF TOO INTIMATE SOCIETY',
 b"THERE'S A HEAVY STORM COMING ON I CRIED POINTING TOWARDS THE HORIZON",
 b'WHY SHOULD THE MISTRESS OF THE VALES OF HAR UTTER A SIGH',
 b'THE AXE STRUCK DEEP INTO THE VERY PITH THE TREE FELL TO THE EARTH WITH A SIGH HE FELT A PANG IT WAS LIKE A SWOON HE COULD NOT THINK OF HAPPINESS FOR HE WAS SORROWFUL AT BEING SEPARATED FROM HIS HOME FROM THE PLACE WHERE HE HAD SPRUNG UP',
 b'SHE ROSE QUICKLY TO HER FEET WITH AN IMPETUOUS GESTURE THAT MADE HER VISITOR CATCH HER BREATH',
 b'THIS WAS WHAT DID THE MISCHIEF SO FAR AS THE RUNNING AWAY WAS CONCERNED',
 b'UP IN THE SICK ROOM ZORA LAY ON THE LITTLE WHITE BED',
 b'VERSE TWO',
 b'P S PRAY SIR EXCUSE ME FOR WRITING TO YOU A SECOND TIME I COULD NOT HELP WRITING P

In [6]:
with open("file.txt", "w") as output:
    output.write(str(strings))

In [7]:
import pickle
with open('gt.pkl', 'wb') as fp:
    pickle.dump(strings, fp)

In [3]:
import pickle
with open ('gt.pkl', 'rb') as fp:
    strings = pickle.load(fp)

In [ ]:
RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/2022-11-08T045935.143694/saved_samples"

import os, re
files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("adversarial.wav")]
adv

In [ ]:
RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/2022-11-08T045935.143694/reconstructed_low_sampled"

import os, re
files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("adversarial_gen.wav")]
adv

In [84]:
from jiwer import wer
wers = []
for id, file in enumerate(adv):
    samplerate, data = wavfile.read(file)
    data = data.astype(np.float32)
    max_int16 = 2**27
    data = data / max_int16
    recons_res = ds2.predict(x = np.array([data]), batch_size= 1)
    gt_len = len(strings[id].decode().split())
    wers.append((wer(strings[id].decode(), recons_res[0]), gt_len))

In [85]:
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

1.2311067771818625

In [80]:
from jiwer import wer
wers = []
for id, file in enumerate(adv):
    samplerate, data = wavfile.read(file)
    recons_res = ds2.predict(x = np.array([data]), batch_size= 1)
    gt_len = len(strings[id].decode().split())
    wers.append((wer(strings[id].decode(), recons_res[0]), gt_len))

In [81]:
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

1.6021452949780595

In [24]:
import numpy as np
np.average(wers)

0.20002364828095132

In [29]:
# eps 0.001
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

0.17698683568990736

In [54]:
# eps 0.001 (no defense)
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

0.15504631886884446

In [32]:
# eps 0.01 (defense)
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

0.6528522671867382

In [48]:
# eps 0.01 (not defense)
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

0.5870307167235495

In [35]:
# eps 0.1 (defense)
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

1.6416382252559727

In [40]:
# eps 0.1 (not defense)
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

1.386153096050707

In [ ]:
wers

In [64]:
np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers])

0.6723549488054608

In [66]:
import torch
from speechbrain.pretrained import HIFIGAN
hifi_gan = HIFIGAN.from_hparams(source="speechbrain/tts-hifigan-ljspeech", savedir="tmpdir", run_opts={"device":"cuda"} )
mel_specs = torch.rand(2, 80,298)
waveforms = hifi_gan.decode_batch(mel_specs)


In [67]:
waveforms

tensor([[[ 0.2882,  0.0663, -0.4731,  ...,  0.6131,  0.5997,  0.5510]],

        [[ 0.3430,  0.1186, -0.4466,  ...,  0.6641,  0.6654,  0.6347]]],
       device='cuda:0')

In [68]:
import librosa

In [71]:
wav, sr = librosa.load('/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/0_adversarial.wav')

In [92]:
wav

array([ 0.00475076,  0.00178127, -0.00507048, ...,  0.00157706,
       -0.00039677, -0.0016528 ], dtype=float32)

In [149]:
waveform, sample_rate = torchaudio.load('example_TTS.wav', normalize=True)
get_spec = torchaudio.transforms.Spectrogram(n_fft=158)
mel_specs = get_spec(waveform)

In [152]:
np.log2(mel_specs)

tensor([[[ -7.4205,  -9.2119,  -9.9385,  ..., -13.7250, -17.9394, -13.1379],
         [-11.5950,  -6.5161,  -8.9111,  ..., -13.3054, -17.1327, -13.1300],
         [-11.8416,  -5.2347,  -6.7549,  ..., -12.3361, -14.1525, -15.9580],
         ...,
         [-27.6712, -25.6583, -29.3428,  ..., -13.2488, -28.2330, -22.2129],
         [-24.1004, -26.5098, -23.9516,  ..., -14.2485, -24.6600, -22.6992],
         [-22.4043, -23.1414, -22.3180,  ..., -14.7242, -25.4857, -22.6664]]])

In [145]:
mel_specs.shape

torch.Size([1, 80, 1611])

In [146]:
waveforms = hifi_gan.decode_batch(np.log(mel_specs))

In [95]:
np.min(np.array(waveforms.cpu()))

-1.0

In [147]:
import torchaudio
torchaudio.save('example_TTS.wav',waveforms.cpu().squeeze(1), sample_rate)

In [ ]:
import torchaudio
from speechbrain.pretrained import Tacotron2
from speechbrain.pretrained import HIFIGAN

# Intialize TTS (tacotron2) and Vocoder (HiFIGAN)
tacotron2 = Tacotron2.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tts")
hifi_gan = HIFIGAN.from_hparams(source="speechbrain/tts-hifigan-ljspeech", savedir="tmpdir_vocoder")

# Running the TTS
mel_output, mel_length, alignment = tacotron2.encode_text("Mary had a little lamb")

print(mel_output)

mel_output += torch.from_numpy(np.random.rand(*mel_output.shape)).double()

mel_output = mel_output.to(torch.double)

# Running Vocoder (spectrogram-to-waveform)
waveforms = hifi_gan.decode_batch(mel_output)

# Save the waverform
torchaudio.save('example_TTS.wav',waveforms.squeeze(1), 22050)

In [ ]:
np.random.rand(*mel_output.shape)

In [126]:
import argparse
import logging
import os

import librosa
import numpy as np
import soundfile as sf
import yaml

from tqdm import tqdm


def logmelfilterbank(
    audio,
    sampling_rate,
    fft_size=1024,
    hop_size=256,
    win_length=None,
    window="hann",
    num_mels=80,
    fmin=None,
    fmax=None,
    eps=1e-10,
    log_base=10.0,
):
    """Compute log-Mel filterbank feature.
    Args:
        audio (ndarray): Audio signal (T,).
        sampling_rate (int): Sampling rate.
        fft_size (int): FFT size.
        hop_size (int): Hop size.
        win_length (int): Window length. If set to None, it will be the same as fft_size.
        window (str): Window function type.
        num_mels (int): Number of mel basis.
        fmin (int): Minimum frequency in mel basis calculation.
        fmax (int): Maximum frequency in mel basis calculation.
        eps (float): Epsilon value to avoid inf in log calculation.
        log_base (float): Log base. If set to None, use np.log.
    Returns:
        ndarray: Log Mel filterbank feature (#frames, num_mels).
    """
    # get amplitude spectrogram
    x_stft = librosa.stft(
        audio,
        n_fft=fft_size,
        hop_length=hop_size,
        win_length=win_length,
        window=window,
        pad_mode="reflect",
    )
    spc = np.abs(x_stft).T  # (#frames, #bins)

    # get mel basis
    fmin = 0 if fmin is None else fmin
    fmax = sampling_rate / 2 if fmax is None else fmax
    mel_basis = librosa.filters.mel(
        sr=sampling_rate,
        n_fft=fft_size,
        n_mels=num_mels,
        fmin=fmin,
        fmax=fmax,
    )
    mel = np.maximum(eps, np.dot(spc, mel_basis.T))

    if log_base is None:
        return np.log(mel)
    elif log_base == 10.0:
        return np.log10(mel)
    elif log_base == 2.0:
        return np.log2(mel)
    else:
        raise ValueError(f"{log_base} is not supported.")

In [128]:
logmelfilterbank(np.array(waveform), sample_rate)

ValueError: shapes (141,513,1) and (513,80) not aligned: 1 (dim 2) != 513 (dim 0)

In [175]:
import pickle

with open("/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/predictions.pkl", 'rb') as f:
    pred = pickle.load(f)

In [ ]:
pred

In [7]:
eps_e_4 = "2022-11-08T052340.454091"
eps_e_3 = "2022-11-08T051608.443297"
eps_e_2 = "2022-11-08T050918.786720"
eps_e_1 = "2022-11-08T045935.143694"
eps_2e_1 = ""

In [7]:
def word_error_rate(y, y_pred):
    import numpy as np
    """
    Return the word error rate for a batch of transcriptions.
    """
    if isinstance(y, bytes):
        y = y.decode("utf-8")
    elif not isinstance(y, str):
        raise TypeError(f"y is of type {type(y)}, expected string or bytes")
    if isinstance(y_pred, bytes):
        y_pred = y_pred.decode("utf-8")
    elif not isinstance(y_pred, str):
        raise TypeError(f"y_pred is of type {type(y_pred)}, expected string or bytes")
    reference = y.split()
    hypothesis = y_pred.split()

    r_length = len(reference)
    h_length = len(hypothesis)
    matrix = np.zeros((r_length + 1, h_length + 1))
    for i in range(r_length + 1):
        for j in range(h_length + 1):
            if i == 0:
                matrix[0][j] = j
            elif j == 0:
                matrix[i][0] = i
    for i in range(1, r_length + 1):
        for j in range(1, h_length + 1):
            if reference[i - 1] == hypothesis[j - 1]:
                matrix[i][j] = matrix[i - 1][j - 1]
            else:
                substitute = matrix[i - 1][j - 1] + 1
                insertion = matrix[i][j - 1] + 1
                deletion = matrix[i - 1][j] + 1
                matrix[i][j] = min(substitute, insertion, deletion)
    return (matrix[r_length][h_length], r_length)

In [14]:
def no_defense(folder):
    RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/"+folder+"/saved_samples"

    import os, re
    import numpy as np
    from scipy.io import wavfile
    files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

    files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

    adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("adversarial.wav")]
    adv
    from jiwer import wer
    wers = []
    for id, file in enumerate(adv):
        samplerate, data = wavfile.read(file)
        recons_res = ds2.predict(x = np.array([data]), batch_size= 1)
        # print(recons_res)
        gt_len = len(strings[id].decode().split())
        # wers.append((wer(strings[id].decode(), recons_res[0]), gt_len))
        wers.append(word_error_rate(strings[id], recons_res[0]))

    print(wers)
    # return np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers]), np.average([wer for wer, _ in wers])
    return np.sum([error for error, _ in wers]) / np.sum([length for _, length in wers])

In [15]:
def defense(folder):
    RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/"+folder+"/reconstructed_low_sampled"
    import os, re
    import numpy as np
    from scipy.io import wavfile
    files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

    files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

    adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("adversarial_gen.wav")]
    adv
    from jiwer import wer
    wers = []
    for id, file in enumerate(adv):
        samplerate, data = wavfile.read(file)
        data = data.astype(np.float32)
        max_int16 = 2**40
        data = data / max_int16
        recons_res = ds2.predict(x = np.array([data]), batch_size= 1)
        # print(recons_res)
        gt_len = len(strings[id].decode().split())
        # wers.append((wer(strings[id].decode(), recons_res[0]), gt_len))
        wers.append(word_error_rate(strings[id], recons_res[0]))

    print(wers)
    # return np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers]), np.average([wer for wer, _ in wers])
    return np.sum([error for error, _ in wers]) / np.sum([length for _, length in wers])

In [64]:
def defense_hifi(folder):
    RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/"+folder+"/reconstructed_low_sampled_hifi"
    import os, re
    import numpy as np
    from scipy.io import wavfile
    files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

    files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

    adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("adversarial_gen.wav")]
    adv
    from jiwer import wer
    wers = []
    for id, file in enumerate(adv):
        samplerate, data = wavfile.read(file)
        data = data.astype(np.float32)
        max_int16 = 2**40
        data = data / max_int16
        recons_res = ds2.predict(x = np.array([data]), batch_size= 1)
        gt_len = len(strings[id].decode().split())
        # wers.append((wer(strings[id].decode(), recons_res[0]), gt_len))
        wers.append(word_error_rate(strings[id], recons_res[0]))

    # return np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers]), np.average([wer for wer, _ in wers])
    return np.sum([error for error, _ in wers]) / np.sum([length for _, length in wers])

In [72]:
def defense_arc(folder):
    RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/"+folder+"/reconstructed_arc"
    import os, re
    import numpy as np
    from scipy.io import wavfile
    files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

    files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

    adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("adversarial_gen.wav")]
    adv
    from jiwer import wer
    wers = []
    for id, file in enumerate(adv):
        samplerate, data = wavfile.read(file)
        data = data.astype(np.float32)
        max_int16 = 2**40
        data = data / max_int16
        recons_res = ds2.predict(x = np.array([data]), batch_size= 1)
        gt_len = len(strings[id].decode().split())
        # wers.append((wer(strings[id].decode(), recons_res[0]), gt_len))
        wers.append(word_error_rate(strings[id], recons_res[0]))

    # return np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers]), np.average([wer for wer, _ in wers])
    return np.sum([error for error, _ in wers]) / np.sum([length for _, length in wers])

In [22]:
def defense_lj_wave(folder):
    RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/"+folder+"/reconstructed_lj_wave_low_sampled"
    import os, re
    import numpy as np
    from scipy.io import wavfile
    files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

    files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

    adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("adversarial_gen.wav")]
    adv
    from jiwer import wer
    wers = []
    for id, file in enumerate(adv):
        samplerate, data = wavfile.read(file)
        data = data.astype(np.float32)
        max_int16 = 2**40
        data = data / max_int16
        recons_res = ds2.predict(x = np.array([data]), batch_size= 1)
        # print(recons_res)
        gt_len = len(strings[id].decode().split())
        # wers.append((wer(strings[id].decode(), recons_res[0]), gt_len))
        wers.append(word_error_rate(strings[id], recons_res[0]))

    print(wers)
    # return np.sum([wer * weight for wer, weight in wers]) / np.sum([weight for _, weight in wers]), np.average([wer for wer, _ in wers])
    return np.sum([error for error, _ in wers]) / np.sum([length for _, length in wers])

In [94]:
print(no_defense(eps_e_4))
print(defense(eps_e_4))

print(no_defense(eps_e_3))
print(defense(eps_e_3))

print(no_defense(eps_e_2))
print(defense(eps_e_2))

print(no_defense(eps_e_1))
print(defense(eps_e_1))

0.1053144807411019
0.1657727937591419
0.15504631886884446
0.18917601170160897
0.7357386640663092
0.5343734763529986
1.6021452949780595
1.2311067771818625


In [95]:
print(no_defense(eps_e_4))
print(defense(eps_e_4))

print(no_defense(eps_e_3))
print(defense(eps_e_3))

print(no_defense(eps_e_2))
print(defense(eps_e_2))

print(no_defense(eps_e_1))
print(defense(eps_e_1))

0.1053144807411019
0.1657727937591419
0.15504631886884446
0.18917601170160897
0.7357386640663092
0.5343734763529986
1.6021452949780595
1.2311067771818625


In [ ]:
from art.attacks.evasion import ProjectedGradientDescentPyTorch, ProjectedGradientDescent
pgd = ProjectedGradientDescent(ds2, norm='inf', eps=0.01, eps_step=0.002, max_iter=7)
from scipy.io import wavfile
import numpy as np
samplerate, data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/36_benign.wav')
adv = pgd.generate(np.array([data]))

In [13]:
def attack(eps, output):
    from scipy.io import wavfile
    import numpy as np
    import os, re
    try:
        os.makedirs(output)
    except:
        pass
    RECONSTRUCTED_LOW_SR = "/home/rni/.armory/outputs/2022-11-08T052340.454091/saved_samples"
    from art.attacks.evasion import ProjectedGradientDescentPyTorch, ProjectedGradientDescent
    pgd = ProjectedGradientDescent(ds2, norm='inf', eps=eps, eps_step=eps/5, max_iter=7, batch_size=1)

    files = [f for f in os.listdir(RECONSTRUCTED_LOW_SR) if f.endswith(".wav")]

    files = sorted(files, key=lambda f: int(re.sub('\D', '', f)))

    adv = [os.path.join(RECONSTRUCTED_LOW_SR, f) for f in files if f.endswith("benign.wav")]
    adv
    from jiwer import wer
    index = 0
    for id, file in enumerate(adv):
        samplerate, data = wavfile.read(file)
        adv_sample = (pgd.generate(np.array([data])))
        wavfile.write(os.path.join(output, str(index)+"_adversarial.wav"), samplerate, adv_sample.T)
        index += 1


In [ ]:
attack(0.001, "/home/rni/.armory/outputs/new_attack_0_001")

In [16]:
print(no_defense("new_attack_0_001"))

[(16.0, 33), (8.0, 19), (6.0, 12), (8.0, 12), (12.0, 50), (5.0, 17), (9.0, 14), (5.0, 12), (2.0, 2), (25.0, 54), (32.0, 59), (15.0, 22), (5.0, 17), (4.0, 8), (3.0, 8), (6.0, 20), (3.0, 5), (19.0, 43), (3.0, 6), (1.0, 4), (14.0, 21), (16.0, 27), (14.0, 22), (15.0, 27), (8.0, 12), (10.0, 17), (11.0, 26), (3.0, 4), (14.0, 43), (8.0, 18), (19.0, 29), (1.0, 7), (6.0, 24), (17.0, 27), (5.0, 7), (13.0, 23), (4.0, 14), (3.0, 9), (6.0, 8), (5.0, 6), (9.0, 15), (9.0, 14), (3.0, 27), (12.0, 33), (3.0, 8), (13.0, 33), (7.0, 19), (2.0, 18), (10.0, 43), (4.0, 11), (3.0, 7), (5.0, 27), (4.0, 9), (19.0, 31), (7.0, 26), (4.0, 13), (2.0, 2), (9.0, 24), (0.0, 13), (18.0, 43), (7.0, 12), (16.0, 40), (9.0, 31), (13.0, 18), (1.0, 7), (5.0, 23), (12.0, 19), (9.0, 13), (12.0, 30), (5.0, 18), (9.0, 27), (12.0, 17), (31.0, 61), (6.0, 9), (4.0, 7), (14.0, 34), (5.0, 17), (7.0, 10), (7.0, 25), (5.0, 7), (7.0, 11), (5.0, 6), (4.0, 9), (9.0, 31), (15.0, 46), (33.0, 50), (13.0, 40), (5.0, 16), (5.0, 18), (1.0, 2), (

In [17]:
print(defense("new_attack_0_001"))

[(13.0, 33), (5.0, 19), (3.0, 12), (4.0, 12), (8.0, 50), (2.0, 17), (0.0, 14), (2.0, 12), (2.0, 2), (17.0, 54), (27.0, 59), (8.0, 22), (8.0, 17), (4.0, 8), (1.0, 8), (3.0, 20), (3.0, 5), (12.0, 43), (2.0, 6), (0.0, 4), (8.0, 21), (8.0, 27), (5.0, 22), (11.0, 27), (6.0, 12), (6.0, 17), (8.0, 26), (0.0, 4), (8.0, 43), (4.0, 18), (10.0, 29), (1.0, 7), (5.0, 24), (14.0, 27), (4.0, 7), (10.0, 23), (3.0, 14), (2.0, 9), (5.0, 8), (2.0, 6), (5.0, 15), (7.0, 14), (2.0, 27), (10.0, 33), (2.0, 8), (8.0, 33), (6.0, 19), (1.0, 18), (7.0, 43), (3.0, 11), (2.0, 7), (6.0, 27), (2.0, 9), (16.0, 31), (4.0, 26), (2.0, 13), (2.0, 2), (2.0, 24), (1.0, 13), (10.0, 43), (5.0, 12), (9.0, 40), (11.0, 31), (9.0, 18), (0.0, 7), (4.0, 23), (10.0, 19), (3.0, 13), (7.0, 30), (4.0, 18), (1.0, 27), (3.0, 17), (23.0, 61), (3.0, 9), (2.0, 7), (13.0, 34), (1.0, 17), (5.0, 10), (4.0, 25), (4.0, 7), (3.0, 11), (0.0, 6), (4.0, 9), (11.0, 31), (13.0, 46), (17.0, 50), (8.0, 40), (1.0, 16), (3.0, 18), (0.0, 2), (3.0, 14), (3.

In [ ]:
attack(0.01, "/home/rni/.armory/outputs/new_attack_0_01/saved_samples")


In [18]:
print(no_defense("new_attack_0_01"))
print(defense("new_attack_0_01"))

[(41.0, 33), (22.0, 19), (21.0, 12), (12.0, 12), (63.0, 50), (16.0, 17), (18.0, 14), (11.0, 12), (4.0, 2), (54.0, 54), (58.0, 59), (23.0, 22), (14.0, 17), (7.0, 8), (10.0, 8), (19.0, 20), (6.0, 5), (41.0, 43), (6.0, 6), (5.0, 4), (22.0, 21), (25.0, 27), (43.0, 22), (39.0, 27), (11.0, 12), (17.0, 17), (28.0, 26), (7.0, 4), (47.0, 43), (20.0, 18), (37.0, 29), (15.0, 7), (29.0, 24), (22.0, 27), (8.0, 7), (23.0, 23), (13.0, 14), (15.0, 9), (6.0, 8), (7.0, 6), (15.0, 15), (18.0, 14), (22.0, 27), (30.0, 33), (12.0, 8), (43.0, 33), (14.0, 19), (17.0, 18), (33.0, 43), (15.0, 11), (6.0, 7), (34.0, 27), (15.0, 9), (34.0, 31), (29.0, 26), (12.0, 13), (3.0, 2), (23.0, 24), (12.0, 13), (46.0, 43), (12.0, 12), (45.0, 40), (31.0, 31), (19.0, 18), (5.0, 7), (22.0, 23), (19.0, 19), (12.0, 13), (25.0, 30), (25.0, 18), (31.0, 27), (16.0, 17), (71.0, 61), (21.0, 9), (7.0, 7), (33.0, 34), (18.0, 17), (16.0, 10), (25.0, 25), (10.0, 7), (15.0, 11), (7.0, 6), (9.0, 9), (28.0, 31), (43.0, 46), (66.0, 50), (40.

In [ ]:
attack(0.005, "/home/rni/.armory/outputs/new_attack_0_005/saved_samples")

In [131]:
print(no_defense("new_attack_0_005"))
print(defense("new_attack_0_005"))

0.825938566552901
0.6099463676255485


In [23]:
print(defense_lj_wave("new_attack_0_005"))

[(22.0, 33), (13.0, 19), (9.0, 12), (6.0, 12), (37.0, 50), (4.0, 17), (3.0, 14), (8.0, 12), (2.0, 2), (29.0, 54), (50.0, 59), (21.0, 22), (12.0, 17), (6.0, 8), (3.0, 8), (14.0, 20), (4.0, 5), (17.0, 43), (6.0, 6), (0.0, 4), (15.0, 21), (21.0, 27), (17.0, 22), (20.0, 27), (12.0, 12), (14.0, 17), (16.0, 26), (2.0, 4), (32.0, 43), (7.0, 18), (23.0, 29), (3.0, 7), (18.0, 24), (23.0, 27), (5.0, 7), (21.0, 23), (9.0, 14), (6.0, 9), (6.0, 8), (6.0, 6), (12.0, 15), (11.0, 14), (8.0, 27), (13.0, 33), (5.0, 8), (21.0, 33), (11.0, 19), (4.0, 18), (18.0, 43), (8.0, 11), (3.0, 7), (7.0, 27), (7.0, 9), (26.0, 31), (14.0, 26), (4.0, 13), (2.0, 2), (14.0, 24), (6.0, 13), (31.0, 43), (8.0, 12), (22.0, 40), (24.0, 31), (13.0, 18), (2.0, 7), (9.0, 23), (15.0, 19), (9.0, 13), (21.0, 30), (17.0, 18), (11.0, 27), (11.0, 17), (40.0, 61), (8.0, 9), (3.0, 7), (29.0, 34), (8.0, 17), (10.0, 10), (21.0, 25), (3.0, 7), (9.0, 11), (5.0, 6), (4.0, 9), (17.0, 31), (26.0, 46), (35.0, 50), (19.0, 40), (11.0, 16), (6.0,

In [25]:
print(defense_lj_wave("new_attack_0_01"))

[(35.0, 33), (18.0, 19), (11.0, 12), (8.0, 12), (59.0, 50), (9.0, 17), (10.0, 14), (10.0, 12), (2.0, 2), (41.0, 54), (53.0, 59), (21.0, 22), (13.0, 17), (6.0, 8), (8.0, 8), (16.0, 20), (5.0, 5), (26.0, 43), (6.0, 6), (2.0, 4), (18.0, 21), (24.0, 27), (25.0, 22), (32.0, 27), (11.0, 12), (15.0, 17), (19.0, 26), (3.0, 4), (48.0, 43), (15.0, 18), (32.0, 29), (11.0, 7), (22.0, 24), (22.0, 27), (5.0, 7), (23.0, 23), (10.0, 14), (6.0, 9), (6.0, 8), (5.0, 6), (14.0, 15), (16.0, 14), (14.0, 27), (25.0, 33), (9.0, 8), (26.0, 33), (12.0, 19), (15.0, 18), (26.0, 43), (12.0, 11), (1.0, 7), (18.0, 27), (12.0, 9), (29.0, 31), (20.0, 26), (8.0, 13), (2.0, 2), (21.0, 24), (7.0, 13), (39.0, 43), (11.0, 12), (38.0, 40), (28.0, 31), (14.0, 18), (4.0, 7), (18.0, 23), (18.0, 19), (10.0, 13), (21.0, 30), (21.0, 18), (21.0, 27), (14.0, 17), (54.0, 61), (10.0, 9), (4.0, 7), (25.0, 34), (15.0, 17), (10.0, 10), (22.0, 25), (5.0, 7), (14.0, 11), (5.0, 6), (6.0, 9), (25.0, 31), (32.0, 46), (42.0, 50), (27.0, 40), 

In [24]:
print(defense_lj_wave("new_attack_0"))

[(8.0, 33), (1.0, 19), (2.0, 12), (1.0, 12), (2.0, 50), (0.0, 17), (1.0, 14), (3.0, 12), (2.0, 2), (12.0, 54), (25.0, 59), (3.0, 22), (3.0, 17), (3.0, 8), (0.0, 8), (4.0, 20), (0.0, 5), (6.0, 43), (0.0, 6), (1.0, 4), (7.0, 21), (4.0, 27), (1.0, 22), (2.0, 27), (1.0, 12), (4.0, 17), (5.0, 26), (0.0, 4), (2.0, 43), (2.0, 18), (7.0, 29), (0.0, 7), (3.0, 24), (8.0, 27), (3.0, 7), (4.0, 23), (1.0, 14), (0.0, 9), (5.0, 8), (1.0, 6), (5.0, 15), (1.0, 14), (2.0, 27), (6.0, 33), (1.0, 8), (4.0, 33), (4.0, 19), (1.0, 18), (3.0, 43), (4.0, 11), (1.0, 7), (6.0, 27), (2.0, 9), (12.0, 31), (2.0, 26), (0.0, 13), (3.0, 2), (5.0, 24), (2.0, 13), (10.0, 43), (3.0, 12), (4.0, 40), (6.0, 31), (7.0, 18), (0.0, 7), (2.0, 23), (3.0, 19), (1.0, 13), (4.0, 30), (2.0, 18), (0.0, 27), (2.0, 17), (6.0, 61), (0.0, 9), (0.0, 7), (8.0, 34), (2.0, 17), (4.0, 10), (4.0, 25), (4.0, 7), (0.0, 11), (1.0, 6), (0.0, 9), (3.0, 31), (8.0, 46), (10.0, 50), (5.0, 40), (3.0, 16), (2.0, 18), (0.0, 2), (1.0, 14), (0.0, 4), (7.0, 

In [ ]:
attack(0.0001, "/home/rni/.armory/outputs/new_attack_0_0001/saved_samples")

In [20]:
print(no_defense("new_attack_0_0001"))
print(defense("new_attack_0_0001"))

/home/rni/deepspeech.pytorch/deepspeech_pytorch/model.py:310: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  seq_len = ((seq_len + 2 * m.padding[1] - m.dilation[1] * (m.kernel_size[1] - 1) - 1) // m.stride[1] + 1)


0.16479765967820575
0.17552413456850316


In [ ]:
attack(0.2, "/home/rni/.armory/outputs/new_attack_0_2/saved_samples")

In [54]:
print(no_defense("new_attack_0_2"))
print(defense("new_attack_0_2"))

['I O E O E E E E E E E E E E E E E E E E E E E E E E E E E E E EE E E EE E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E E  E']
['AOR ALOMENT ON THE MATTAM LADA MENA O H E TE O E O TE O O MOIN M N COM LIN N AD M N E MEN TE TE E E IN ING HM N N ON I N  EM EME I O O HM IM N N M  E E O E E I O  E E']
['PIPOIN THE IDLE MEMIN ON HO HOND HEM PON MORNING IMPELMENT L ON HME E METE OT OY OCOMNING THE PEROLOR A HOMMO METO PNING THEM IMPERMENTOMEN ON OF THE MITLE N I E O E']
['OF THE GLIME COME IN PUINTING IN THE TIPEMENT QUITE YO IN LEMING HEN THE GLTIC ADTEN BE COME N I COMN E MN NT HIM AND COM O O MN M TE OM TE']
['O E E  E E E E E E E E E  E E O E E E E E E E E E EE E E E E E E E E E E E E E E E E E E E E E E E E E E  E E E E E E E E E E E E E E E E E E E E E E E E E E E E E  E E E E E E E E E E E E E E E E E E E E E E E EE E E EEEE E E E E E E E E E E EE']
['WON THE PULING MOMEN THE NOMETEN PRM

In [ ]:
attack(0.1, "/home/rni/.armory/outputs/new_attack_0_1/saved_samples")

In [62]:
print(no_defense("new_attack_0_1"))
print(defense("new_attack_0_1"))

[(88.0, 33), (40.0, 19), (34.0, 12), (20.0, 12), (129.0, 50), (41.0, 17), (26.0, 14), (17.0, 12), (10.0, 2), (119.0, 54), (88.0, 59), (52.0, 22), (25.0, 17), (18.0, 8), (16.0, 8), (35.0, 20), (14.0, 5), (103.0, 43), (20.0, 6), (10.0, 4), (39.0, 21), (68.0, 27), (67.0, 22), (65.0, 27), (32.0, 12), (34.0, 17), (39.0, 26), (26.0, 4), (110.0, 43), (63.0, 18), (62.0, 29), (22.0, 7), (64.0, 24), (43.0, 27), (14.0, 7), (45.0, 23), (39.0, 14), (34.0, 9), (23.0, 8), (19.0, 6), (34.0, 15), (50.0, 14), (60.0, 27), (51.0, 33), (25.0, 8), (73.0, 33), (51.0, 19), (20.0, 18), (69.0, 43), (36.0, 11), (17.0, 7), (49.0, 27), (27.0, 9), (63.0, 31), (54.0, 26), (13.0, 13), (16.0, 2), (40.0, 24), (31.0, 13), (123.0, 43), (23.0, 12), (90.0, 40), (60.0, 31), (37.0, 18), (18.0, 7), (42.0, 23), (41.0, 19), (15.0, 13), (36.0, 30), (54.0, 18), (61.0, 27), (68.0, 17), (172.0, 61), (43.0, 9), (17.0, 7), (87.0, 34), (36.0, 17), (26.0, 10), (54.0, 25), (16.0, 7), (35.0, 11), (13.0, 6), (21.0, 9), (80.0, 31), (59.0, 

In [63]:
print(no_defense("new_attack_0"))
print(defense("new_attack_0"))

[(5.0, 33), (1.0, 19), (0.0, 12), (3.0, 12), (3.0, 50), (1.0, 17), (0.0, 14), (3.0, 12), (1.0, 2), (11.0, 54), (14.0, 59), (4.0, 22), (3.0, 17), (2.0, 8), (0.0, 8), (1.0, 20), (0.0, 5), (4.0, 43), (0.0, 6), (1.0, 4), (2.0, 21), (2.0, 27), (1.0, 22), (1.0, 27), (1.0, 12), (1.0, 17), (4.0, 26), (0.0, 4), (2.0, 43), (0.0, 18), (1.0, 29), (0.0, 7), (1.0, 24), (5.0, 27), (0.0, 7), (3.0, 23), (1.0, 14), (0.0, 9), (4.0, 8), (1.0, 6), (5.0, 15), (0.0, 14), (2.0, 27), (6.0, 33), (1.0, 8), (3.0, 33), (3.0, 19), (0.0, 18), (3.0, 43), (2.0, 11), (0.0, 7), (3.0, 27), (2.0, 9), (11.0, 31), (4.0, 26), (0.0, 13), (1.0, 2), (0.0, 24), (2.0, 13), (2.0, 43), (2.0, 12), (3.0, 40), (1.0, 31), (3.0, 18), (2.0, 7), (2.0, 23), (3.0, 19), (0.0, 13), (3.0, 30), (3.0, 18), (1.0, 27), (0.0, 17), (4.0, 61), (0.0, 9), (1.0, 7), (5.0, 34), (0.0, 17), (3.0, 10), (3.0, 25), (5.0, 7), (0.0, 11), (0.0, 6), (0.0, 9), (2.0, 31), (6.0, 46), (8.0, 50), (3.0, 40), (1.0, 16), (2.0, 18), (0.0, 2), (3.0, 14), (0.0, 4), (3.0, 35

In [65]:
print(defense_hifi("new_attack_0"))

/home/rni/deepspeech.pytorch/deepspeech_pytorch/model.py:310: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  seq_len = ((seq_len + 2 * m.padding[1] - m.dilation[1] * (m.kernel_size[1] - 1) - 1) // m.stride[1] + 1)


0.14578254509995126


In [66]:
print(defense_hifi("new_attack_0_0001"))

0.14822038030229157


In [67]:
print(defense_hifi("new_attack_0_001"))

0.2925402242808386


In [68]:
print(defense_hifi("new_attack_0_005"))

0.6474890297415895


In [69]:
print(defense_hifi("new_attack_0_01"))

0.8985860555826426


In [70]:
print(defense_hifi("new_attack_0_1"))

2.0346172598732326


In [74]:
print(defense_hifi("new_attack_0_2"))

2.362262311067772


In [73]:
print(defense_arc("new_attack_0_2"))

/home/rni/deepspeech.pytorch/deepspeech_pytorch/model.py:310: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  seq_len = ((seq_len + 2 * m.padding[1] - m.dilation[1] * (m.kernel_size[1] - 1) - 1) // m.stride[1] + 1)


1.917601170160897


In [75]:
print(defense_arc("new_attack_0"))

0.27011214041930764


In [76]:
print(defense_arc("new_attack_0_0001"))
print(defense_arc("new_attack_0_001"))
print(defense_arc("new_attack_0_005"))
print(defense_arc("new_attack_0_01"))
print(defense_arc("new_attack_0_1"))

0.2749878108239883
0.3627498781082399
0.6426133593369088
0.8459288152120916
1.575329107752316


In [ ]:
arctic_slt_parallel_wavegan.v1

In [51]:
import pickle
with open("/home/rni/.armory/outputs/2022-11-08T044459.820965/saved_samples/predictions.pkl", 'rb') as f:
    pred_0_2 = pickle.load(f)

In [52]:
pred_0_2

{0: {'ground truth': array([b"BRIGHTER THAN EARLY DAWN'S MOST BRILLIANT DYE ARE BLOWN CLEAR BANDS OF COLOR THROUGH THE SKY THAT SWIRL AND SWEEP AND MEET TO BREAK AND FOAM LIKE RAINBOW VEILS UPON A BUBBLE'S DOME"],
        dtype=object),
  'predicted': array(['WHATT AND O L DP OAD DOND WOAT I LITE NAT A GOD NO HAONE WHAT OTNAND NOTT ON BAT HAM DE PECEOLDLIK ACA NOT LEOKI ON HANOTETHAN OT PUT OOCPOD A ADAOT ALOT AND IAGLUP AN ANE UT T  NOT LET THAN LIDHRLAN RAL ROUDLY LOOK AT HECLTET HOT OUT  HACADHE LET O  THIMEN OAVT I CHOE OMNAN THEN MODED UNDRAITDTA L AEGAD TAT GETDI HD PE THARE LITTLTLO'],
        dtype='<U336')},
 1: {'ground truth': array([b'I AM NOT GOOD ENOUGH FOR YOU AND YOU MUST BE KEPT FROM THE CONTAMINATION OF TOO INTIMATE SOCIETY'],
        dtype=object),
  'predicted': array([''], dtype='<U1')},
 2: {'ground truth': array([b"THERE'S A HEAVY STORM COMING ON I CRIED POINTING TOWARDS THE HORIZON"],
        dtype=object),
  'predicted': array([' LORD LIGREDE HAN GLAD WHA NOTMI

In [4]:
imp = ImperceptibleASRPyTorch(ds2, eps=0.01, max_iter_1=100, max_iter_2=25, learning_rate_1=8e-4, learning_rate_2=8e-7, decrease_factor_eps=0.5)

In [ ]:
from scipy.io import wavfile
import numpy as np
samplerate, data = wavfile.read('/home/rni/.armory/outputs/2022-11-08T050918.786720/saved_samples/36_benign.wav')
adv = imp.generate(np.array(np.array([data])), np.array(["WE WON'T TALK ABOUT HER ANY MORE IF YOU'D RATHER NOT WE INDEED"]))

In [8]:
print(ds2.predict(x = adv, batch_size= 1))
print(ds2.predict(x = np.array([data]), batch_size= 1))

/home/rni/deepspeech.pytorch/deepspeech_pytorch/model.py:310: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  seq_len = ((seq_len + 2 * m.padding[1] - m.dilation[1] * (m.kernel_size[1] - 1) - 1) // m.stride[1] + 1)


["WE WON'T TALK ABOUT HER ANY MORE IF YOU'D RATHER NOT WE INDEED"]
["AND ALL HIS BROTHERS AND SISTERS STOOD ROUND AND LISTENED WITH THEIR MOUTH'S OPEN"]


In [135]:
strings[36]

b'AND ALL HIS BROTHERS AND SISTERS STOOD ROUND AND LISTENED WITH THEIR MOUTHS OPEN'

In [141]:
strings[55]

b"WE WON'T TALK ABOUT HER ANY MORE IF YOU'D RATHER NOT WE INDEED"

In [9]:
wavfile.write("targeted.wav", samplerate, adv.T)

In [77]:
import numpy as np
import matplotlib.pyplot as plt

import librosa
import librosa.display

In [118]:
gen_y, sr = librosa.load("/home/rni/.armory/outputs/new_attack_0_001/reconstructed_low_sampled/1_adversarial_gen.wav")

In [119]:
adv_y, sr = librosa.load("/home/rni/.armory/outputs/new_attack_0_001/saved_samples/1_adversarial.wav")

In [120]:
y = adv_y - gen_y[:143766]

In [121]:
y

array([0.00175731, 0.0017928 , 0.00039347, ..., 0.00059287, 0.00134018,
       0.00188768], dtype=float32)

In [138]:
y, sr = librosa.load("/home/rni/.armory/outputs/new_attack_0_01/reconstructed_low_sampled/1_adversarial_gen.wav")

In [139]:
adv_y, sr = librosa.load("/home/rni/.armory/outputs/new_attack_0_01/saved_samples/1_adversarial.wav")

In [140]:
adv_y, y

(array([-0.0016499 , -0.0091753 , -0.00927687, ..., -0.00624545,
         0.00013948,  0.00585343], dtype=float32),
 array([-0.01224005, -0.01573675, -0.01142786, ...,  0.00808989,
         0.00590313,  0.        ], dtype=float32))

In [146]:
D = librosa.stft(y)  # STFT of y
S_db = librosa.amplitude_to_db(np.abs(D), ref=np.max)

In [147]:
D_adv = librosa.stft(adv_y)  # STFT of y
S_db_adv = librosa.amplitude_to_db(np.abs(D_adv), ref=np.max)

In [149]:
S_db = S_db_adv - S_db[:,:281]

In [150]:
np.sum(S_db)

179856.05

In [151]:
fig, ax = plt.subplots()
img = librosa.display.specshow(S_db, ax=ax)
fig.colorbar(img, ax=ax)

In [ ]:
fig.savefig("diff_0_01.png")